git:
  depth: 3

language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

env:
  - DB=sqlite
  - DB=postgres

matrix:
  fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/php.ini
  - composer install --dev
  - npm install

script:
  - ./node_modules/.bin/jshint assets/js/{core,components}
  - ./vendor/bin/phpunit -c tests/units.$DB.xml
  - ./vendor/bin/phpunit tests/configtest
